app:
  name: "Language Placement"
  scheme: http
  host: localhost:3000
  relative_url_root: /
  full_url: http://localhost:3000

# Overwrite this in production
secret_token: ''

urn_namespaces:
- "urn:biola:language-placement:"
- "urn:biola:apps:all:"

cas:
  url: "https://login.biola.edu/cas"

webcape:
  acct:  # set in settings.local.yml
  pass:  # set in settings.local.yml
  pin:
